### ISSUE TITLE
Can't Access 4chanX Settings

### ISSUE THREAD

**Issue by galaxite** [Catgrills/Pygmalion#3]
As part of the instructions to set up the Pygmalion user style, I am supposed to import 4chanX settings. However, there doesn't appear to be any way to do so. I can import OneeChan settings because there's a menu for it at the top, but clicking the "settings" menu leads to the native 4chan extension, and the hamburger menu on the top left is not clickable.

**Comment by Catgrills** [comment]
Isn't there a monkey wrench icon ?
<img src="https://i.imgur.com/yHCB3Hj.jpg"></img>

As for the hamburger menu, you have to install <a href="https://greasyfork.org/en/scripts/38761-4chan-misc-edition">4chan : Misc Edition</a>

**Comment by galaxite** [comment]
No, I don't have a wrench icon. Here's what the header of /a/ looks like, in comparison to the picture you posted:

![pygmalion](https://user-images.githubusercontent.com/34804471/44229234-6b5fa800-a165-11e8-993e-10f0fa48c085.png)
I left the ViolentMonkey window open so you could see that I have both OneeChan and 4chan: Misc Edition installed.

**Comment by Catgrills** [comment]
Looks like you didn't install 4chanX, that's why you can't access 4chanX settings. As for the hamburger icon, it might appears after you installed the said script.

**Comment by galaxite** [comment]
Just went back through the version history of the readme and found the link to the regular 4chanX script. I installed it and everything works fine now! I will suggest adding the link to the current version of the readme, though.
